name: Bug report
description: If you've confirmed something is broken, create a bug report.
title: "[Bug report] <description>"
labels: [needs triage]
body:
  - type: checkboxes
    id: prereqs
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    id: update-title
    attributes:
      label: Update the issue title
      description: Replace `<description> with a description of the bug
      options:
        - label: I have updated the title
          required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Run `abbr profile` and paste the result here.
      render: shell
    validations:
      required: true
  - type: dropdown
    id: installation-method
    attributes:
      label: Installation method
      description: Select the installation method you use.
      options:
        - Plugin manager
        - Homebrew
        - Manual
        - Other
        - Don't Know
    validations:
      required: true
  - type: textarea
    id: installation-method-details
    attributes:
      label: Installation method details
      description: |
        If you use a plugin manager, which one and what version?

        If you selected "Manual" or "Other" provide any info you think might be useful.

        If you selected "Don't Know", run `echo $ABBR_SOURCE_PATH` and paste the output here. (If the output includes sensitive information, censor it - for example `/Users/myusername/zsh-abbr`)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
